import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./share/Navbar";
import Footer from "./share/Footer";

const concret = Josefin_Sans({ subsets: ["latin"], weight: "400" });

export const metadata = {
  icon: "favicon.ico",
  title: "WritePress - Clean Blog HTML template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${concret.className} dark:bg-dark dark:text-white`}>
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
